export const PortfolioData = [
    {
        id: 1,
        name: 'Landing Page Website',
        skill: 'WEB DEVELOPMENT | VANILLA JAVASCRIPT',
        img: '/img/Screenshot (51).png',
        detail: `A project with no frame works no APIS calls, A good landing page. click on the button below to preview live page`,
        link: 'https://princeizekor.github.io/javascriptspace/Crowdfunding.html',
    },
    {
        id: 2,
        name: 'Fylio Website',
        skill: 'WEB DEVELOPMENT | PURE CSS',
        img: '/img/Screenshot (57).png',
        detail: `A project with no frame works no APIS calls, A good landing page. click on the button below to preview live page`,
        link: 'https://princeizekor.github.io/figma/sidehustle.html',
    },
    {
        id: 3,
        name: 'Dashboard Website',
        skill: 'WEB DEVELOPMENT | PURE CSS',
        img: '/img/Screenshot (53).png',
        detail: `A project with no frame works no APIS calls, A well designed dashboard page. click on the button below to preview live page`,
        link: 'https://princeizekor.github.io/www.project.com/promote.html',
    },
    {
        id: 4,
        name: 'SignUp Page',
        skill: 'WEB DEVELOPMENT | PURE CSS',
        img: '/img/Screenshot (56).png',
        detail: `A project with no frame works no APIS calls, A well designed sign-up page. click on the button below to preview live page`,
        link: 'https://princeizekor.github.io/figma/index.html',
    },
    {
        id: 5,
        name: 'Parallel Landing Page',
        skill: 'WEB DEVELOPMENT | PURE CSS3',
        img: '/img/Screenshot (54).png',
        detail: `A project with no frame works no APIS calls, Page built base on test project. click on the button below to preview live page`,
        link: 'https://princeizekor.github.io/Mycode/employees.html',
    },
    {
        id: 6,
        name: 'Parallel Landing Page',
        skill: 'WEB DEVELOPMENT | PURE CSS3',
        img: '/img/Screenshot (55).png',
        detail: `A project with no frame works no APIS calls, Page built base on test project. click on the button below to preview live page`,
        link: 'https://princeizekor.github.io/Mycode/outer.html',
    },
    {
        id: 7,
        name: 'Rest Country Api',
        skill: 'WEB DEVELOPMENT | HTML | CSS | JAVASCRIPT',
        img: '/img/Screenshot (64).png',
        detail: `A project with no frame works, An API website to discover Countries, A well
        built and responsive api website. click on the button below to preview live page`,
        link: 'https://princeizekor.github.io/CountriesAll/Countries.html',
    },
    {
        id: 8,
        name: 'Url Shortener Website',
        skill: 'WEB DEVELOPMENT | HTML | CSS | JAVASCRIPT',
        img: '/img/Screenshot (66).png',
        detail: `A project with noframe works, An API website which shortens any link which is
        passed on to it and return the shortened links in different form. click on the button below to preview live page`,
        link: 'https://princeizekor.github.io/link-shorten-website/url.html',
    },
    {
        id: 9,
        name: 'CountDown Time Website',
        skill: 'WEB DEVELOPMENT | HTML | CSS | JAVASCRIPT',
        img: '/img/Screenshot (65).png',
        detail: `A project with no frame works, no APIS calls, A countdown website challenge from
        FRONTEND MENTOR. click on the button below to preview live page`,
        link: 'https://princeizekor.github.io/Countdown/',
    },
    {
        id: 10,
        name: 'Api Tracker Map',
        skill: 'WEB DEVELOPMENT | HTML | CSS | JAVASCRIPT',
        img: '/img/Screenshot (67).png',
        detail: `A project with noframe works, An API website which is able to get your ip
        location anywhere in the world, resposive and more. click on the button below to preview live page`,
        link: 'https://princeizekor.github.io/ipaddress/',
    },
    {
        id: 11,
        name: 'ApplyForMe Website',
        skill: 'WEB DEVELOPMENT | HTML | CSS | JAVASCRIPT | REACT',
        img: '/img/Screenshot (125).png',
        detail: `Website built based on team work in the zuri internship. click on the button below to preview live page`,
        link: 'https://applyforme.app/',
    },
    {
        id: 12,
        name: 'User DashBoard',
        skill: 'WEB DEVELOPMENT | HTML | CSS | JAVASCRIPT | REACT',
        img: '/img/Screenshot (124).png',
        detail: `Website built based on a challenge in the zuri internship. click on the button below to preview live page`,
        link: 'https://paulizekor-hng9-stage2-project.netlify.app/',
    },
    {
        id: 13,
        name: 'Meta BNB',
        skill: 'WEB DEVELOPMENT | HTML | CSS | JAVASCRIPT | REACT',
        img: '/img/Screenshot (123).png',
        detail: `Website built based on a challenge in the zuri internship. click on the button below to preview live page`,
        link: 'https://paulizekor-hng9-stage3-project.netlify.app/',
    }
]